### PR TITLE
Migrate to updated sunburst diagram with playback and other fixes

### LINKED ISSUE #9: Migrate to the fun zoomable sunburst diagram
- Example: https://observablehq.com/@d3/zoomable-sunburst
- Requires turning `.csv` to a hierarchical `.json`. See https://d3js.org/d3-hierarchy/stratify
- @staylor7 's attempt: https://observablehq.com/d/6a5d607535b9bd1b

### PR DESCRIPTION
**Pull request by quinnouyang**
- Migrates #11 
- Fixes type issues (with potential errors)
- Organizes utilities and logic
- Removes redundant and deprecated code

### CODE REVIEW

**Comment by quinnouyang** [comment]
Forwarding comments from previous draft PR: https://github.com/staylor7/rare-diseases/pull/11#pullrequestreview-1865717826

File: src/audio.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+}
+
+export function extractChakraName(name: string) {
+  return name.match(/\(([^)]+)\)/)?.[1]; // Extracts chakra name from paranthesis (e.g. "endocrine (ritu)" -> "ritu")
+}
+
+export function getRowNumberForDisease(diseaseName: string) {
+  const diseaseEntry = CSV.find((entry) => entry.Disease === diseaseName);
+  return diseaseEntry ? diseaseEntry.index : null;
+}
```
Comment (quinnouyang) [inline src/audio.ts:40]: Nice-to-have after migration: do not rely on CSV and store audio paths etc. in JSON

File: src/csv2json.js
Comment (quinnouyang) [inline src/csv2json.js:1]: Restoring this script for future use, though consider moving it outside the `src/`. While we can type it, executing raw TS files are annoying.

File: src/main.ts [hunk 2]
```diff
@@ -1,8 +1,191 @@
...
+} from "./audio";
+import { Datum, DatumNode, Rectangle } from "./types";
 
-if (container) draw(data, container);
+const CONTAINER = document.getElementById("sunburst");
+if (!CONTAINER) throw new Error("No container found with the ID 'sunburst'");
+
+const WIDTH = 928; // px
+const HEIGHT = WIDTH; // px
+const RADIUS = WIDTH / 6; // px
```
Comment (quinnouyang) [inline src/main.ts:30]: TODO after migration: un-hard-code

File: src/main.ts [hunk 3]
```diff
@@ -1,8 +1,191 @@
...
+  quantize(interpolateRainbow, DATA.children?.length ?? 0 + 1)
+);
+
+const hierarchyNode = hierarchy(DATA)
+  .sum((d) => d.value || 0)
+  .sort((a, b) => (b.value || 0) - (a.value || 0));
+
+const root = partition<Datum>().size([2 * Math.PI, hierarchyNode.height + 1])(
+  hierarchyNode
+) as DatumNode; // WARNING: Unvalidated typing (assumes all `DatumNode.current` and `DatumNode.target` will exist)
```
Comment (quinnouyang) [inline src/main.ts:44]: Not sure how this works

File: src/types.ts [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+  /**
+   * The right edge of the rectangle.
+   */
+  x1: number;
+
+  /**
+   * The bottom edge of the rectangle.
+   */
+  y1: number;
+};
```
Comment (quinnouyang) [inline src/types.ts:36]: TODO after migration: determine what each of these mean in the sunburst (we do not use them as commented)

File: src/types.ts [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+/**
+ * Stores current and target locations for interactions
+ * @todo Verify this is the correct polymorphism (Should {@link DatumNode} and {@link Rectangle} should be somewhat interchangeable?)
```
Comment (quinnouyang) [inline src/types.ts:40]: This inheritance feels wrong, e.g. `shouldBeVisible` currently accepts a `Rectangle` but the initial demo implied a `Datum`

Can ignore for now...

**Review by quinnouyang — COMMENTED** [review]
Mostly TODOs, nice-to-haves, and questions for later. @SallyXue-0114 LMK your thoughts too
