### PR TITLE
On-click disease information popups, crossfading, and updated hierarchy.json

### LINKED ISSUE #14: Add crossfading

### LINKED ISSUE #21: Hover over the individual disease for both playback and information
don't need the detail layer circle.
when hover over, pop up window (small) that display detailed informations (that are originally in the detail layer circle) + blurred out the disease circle. 
Also update the hierarchy.json using the new csv

### LINKED ISSUE #22: Rapid clicking between playback elements can cause delays/errors
## To Reproduce

Click between categories and diseases quickly, interrupting their playback
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
```

### PR DESCRIPTION
**Pull request by SallyXue-0114**
- Fixes #21 (see demo) except for the mouseover (now it is through click), quinn maybe you can take a look and try it out?
- Fixes #14 
- Fixes #22

### CODE REVIEW

File: src/popup.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+          // Extract the URL from the text, assuming it's the part after the colon
+          const urlMatch = child.data.name.match(/Link:\s*(.*)/);
+          const url = urlMatch ? urlMatch[1] : "";
+          // Format the URL as a clickable link, but keep 'Link:' as plain text
+          return `<strong>Link:</strong> <a href="${url}" target="_blank" rel="noopener noreferrer" style="color: purple;">${url}</a>`;
+        }
+        // Format other details, making the part before ':' bold
+        return child.data.name.replace(/(^[^:]+):/, "<strong>$1:</strong>");
+      })
+      .join("<br>") ?? "No details available";
```
Comment (quinnouyang) [inline src/popup.ts:27]: Works for now but may be easier to have text elements already templated out and we simply fill in the text content rather than rebuilding them with stringified HTML each time?

File: src/popup.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+        </div>`;
+    popup.style.display = "block";
+    popup.style.position = "fixed";
+    popup.style.left = "50%";
+    popup.style.top = "50%";
+    popup.style.transform = "translate(-50%, -50%)";
+    popup.style.zIndex = "1000";
+
+    sunburst.style.opacity = "0.5";
+  }
```
Comment (quinnouyang) [inline src/popup.ts:43]: Are we only use part of the initial HTML then?

```html
<div
    id="diseasePopup"
    style="
      display: none;
      position: absolute;
      z-index: 10;
      background: white;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
    "
  >
    <button id="closePopupButton" style="float: right">&times;</button>
    <div id="diseaseDetails"></div>
  </div>
```

**Comment by quinnouyang** [comment]
When a user reclicks a chakra, do we want to replay (and fade-in/out) its sound or just ignore the event and continue looping?

For disease audio, I would opt for replaying. (With overlap? Right now it's single-state only so it could clip.)

**Comment by staylor7** [comment]
If the use re-clicks a chakra, I think it would be nice if it could ignore that click and continue playing its sound. But for the disease, if a user reclicks it should play again if possible.

**Comment by quinnouyang** [comment]
Will ignore chakra re-clicks and continue looping. For diseases, should the new audio reset or overlap the previous? (and should it depend on whether the new audio is for the same disease?)
